# https://render.com/docs/blueprint-spec
databases:
  - name: x_db
    ipAllowList: [] # only allow internal connections
    postgresMajorVersion: 14

envVarGroups:
  - name: prod
    envVars:
      - key: APP_ENV
        value: prod
      - key: DATABASE_POOL_SIZE
        value: 40
      - key: DATABASE_URL
        fromDatabase:
          name: x_db
          property: connectionString
        sync: false

services:
  - type: web
    name: x_web
    env: ruby
    buildCommand: "./x build %% ./x db migrate"
    startCommand: "./x api start"
    healthCheckPath: /health
    envVars:
      - fromGroup: prod
  - type: worker
    name: x_worker_queue_listen
    env: ruby
    buildCommand: "./x build"
    startCommand: "./x worker start queue_listen"
    envVars:
      - fromGroup: prod
